name: Build & Publish
on:
  push:
    branches: [main]
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtinth/cd-nixpacks@main
